### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BlawoHD** [jasonwynn10/CrossOnlineCount#1]
How do I use it for the slapper plugin?

**Comment by jasonwynn10** [comment]
It's incomplete at the moment. Actually, I am working out an answer to the question you asked right now to complete it. I need a way to initialize the use and retain the text position of where the online count should go

**Comment by majovec** [comment]
Its now work ?

**Comment by jasonwynn10** [comment]
The plugin has been completed and works very well

**Comment by majovec** [comment]
This fork only for 1 server

**Comment by jasonwynn10** [comment]
what do you mean?

**Comment by majovec** [comment]
this http://play.fylkat.cz/b.png

**Comment by jasonwynn10** [comment]
the plugin is supposed to be used for ip addresses, not DNS addresses. Some DNS addresses might work, but not all will, so you will have to use the actual ip address for those servers

**Comment by majovec** [comment]
same problem

**Comment by jasonwynn10** [comment]
Can you provide steps for exactly what you did in your attempt?
