### ISSUE TITLE
Multiple lines doest work

### ISSUE THREAD

**Issue by Driesboy** [jasonwynn10/CrossOnlineCount#6]
![img_39e1ebd097e6-1](https://user-images.githubusercontent.com/15795262/28995477-70503a80-79ea-11e7-9275-eb23f5315039.jpeg)

command: /slapper spawn Human gamecraftpe.tk:19133 {line} §6Skywars 6b - Tap to join

**Comment by jasonwynn10** [comment]
Upon further inspection the problem was caused because you inserted a space before {line}
