### ISSUE TITLE
Server crashes..

### ISSUE THREAD

**Issue by TheFixerDevelopment** [jasonwynn10/CrossOnlineCount#7]
Do you have to be on ALPHA7 of Pocketmine in order for this to work or can you do this on Pocketmine ALPHA6 as well?

**Comment by jasonwynn10** [comment]
I only tested the plugin on PocketMine alpha7, so I don’t know about alpha6 support. Feel free to test it and tell me what happens!

**Comment by TheFixerDevelopment** [comment]
This is what the error says in Crashdump.
GenisysPro Crash Dump Sat Aug 5 08:43:05 MDT 2017

Error: Declaration of jasonwynn10\CrossOnlineCount\UpdateTask::onRun(int $currentTick) must be compatible with pocketmine\scheduler\Task::onRun($currentTick)
File: /CrossOnlineCount.phar/src/jasonwynn10/CrossOnlineCount/UpdateTask
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : CombinedSlots v0.1.0

Code:
[1] <?php
[2] namespace jasonwynn10\CrossOnlineCount;
[3] 
[4] use pocketmine\scheduler\PluginTask;
[5] 
[6] class UpdateTask extends PluginTask {
[7] 	public function onRun(int $currentTick) {
[8] 		$this->getOwner()->update();
[9] 	}
[10] }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

GenisysPro version: 22a4874a90a239949caff3f687f85ff8b76650d0 [Protocol 113; API 3.0.1]
uname -a: Linux mc35.vgmc.co.uk 2.6.32-696.3.2.el6.x86_64 #1 SMP Tue Jun 20 01:26:55 UTC 2017 x86_64
PHP version: 7.0.19
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 0 seconds
Number of loaded worlds: 0
Players online: 0/200

Loaded plugins:
CustomAlerts 1.7 by EvolSoft for API(s) 1.0.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
PocketVote 2.0.1 by ProjectInfinity for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
EggWars 2.0.0 by ThePullGamesTM for API(s) 3.0.0-ALPHA4, 3.0.0, 3.0.1
Slapper 1.3.5 by jojoe77777 for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6
EconomyAPI 5.7.1-dev1 by onebone for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6
WorldGuard 1 by Muqsit for API(s) 2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8
superBAR 1.6.2 by FaigerSYS for API(s) 2.0.0
Bedwars 4.0.3 by NetherTechnology for API(s) 3.0.0-ALPHA6, 3.0.1
CombinedSlots 0.1.0 by jasonwynn10 for API(s) 3.0.0-ALPHA7
BlockSniper 1.3.1 by Sandertv for API(s) 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
SimpleAuth 1.7.2-php7 by PocketMine Team, shoghicp for API(s) 2.0.0
BlockCmdPE 1.0.0 by Vaivez66, Zeao for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0, 3.0.1
iProtector v4.0#3.1b by Array for API(s) 3.0.0
PurePerms 1.4_INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
BlockPartyPE 1.3.0 by CreeperFace, edited by Zeao. for API(s) 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.1
SignModifier 1.0.0 by wolfdale for API(s) 1.3.1
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 3.0.0-ALPHA6
MobTags 1.0.0 by xXSirButterXx for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
SimpleAuthHelper 2.0.4vgphp7 by aliuly for API(s) 1.12.0
SimpleWarp 3.3.0 by Falkirks for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

I also tested this on Alpha6 and Alpha7.

**Comment by majovec** [comment]
This plugin is only for pmmp on genisys work not work or you dele all string and int from plugin

**Comment by jasonwynn10** [comment]
I’m not supporting PocketMine spoons

**Comment by TheFixerDevelopment** [comment]
But I've tried with Pocketmine also, and still does the same thing.

**Comment by jasonwynn10** [comment]
I’ve tested the plugin repeatedly on pmmp. It works just fine if you do it correctly
